name: checks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_critical_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          ! test -f .env
